import type { SkinPack, ThemeTokens } from './tokens'

const systemSans = 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'
const systemMono = '"SFMono-Regular", "Cascadia Code", "Roboto Mono", ui-monospace, monospace'

function tokens(overrides: Partial<ThemeTokens> & { color: ThemeTokens['color'] }): ThemeTokens {
  return {
    color: overrides.color,
    font: overrides.font ?? {
      sans: systemSans,
      mono: systemMono,
    },
    spacing: overrides.spacing ?? {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '0.75rem',
      lg: '1rem',
    },
    radius: overrides.radius ?? {
      sm: '0.375rem',
      md: '0.5rem',
      lg: '0.75rem',
    },
    shadow: overrides.shadow ?? {
      panel: '0 1px 2px rgb(15 23 42 / 0.08)',
      floating: '0 18px 42px rgb(15 23 42 / 0.18)',
      focus: '0 0 0 3px rgb(59 130 246 / 0.24)',
    },
    motion: overrides.motion ?? {
      fast: '120ms',
      normal: '180ms',
      slow: '280ms',
    },
    density: overrides.density ?? 'comfortable',
  }
}

export const BUILT_IN_SKINS: SkinPack[] = [
  {
    id: 'codex-classic',
    name: 'Codex Classic',
    description: 'Quiet, close to the original desktop feel.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#101216', foreground: '#e5e7eb' },
    chartPalette: ['#2563eb', '#16a34a', '#d97706', '#dc2626', '#7c3aed'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#f4f4f5',
        surface: '#ffffff',
        panel: '#ffffff',
        elevated: '#ffffff',
        text: '#18181b',
        textMuted: '#71717a',
        border: '#e4e4e7',
        accent: '#2563eb',
        danger: '#dc2626',
        warning: '#d97706',
        success: '#16a34a',
        info: '#2563eb',
        codeBackground: '#18181b',
        terminalBackground: '#101216',
      },
    }),
  },
  {
    id: 'control-tower',
    name: 'Control Tower',
    description: 'Dark, dense, status-forward engineering console.',
    isDark: true,
    syntaxTheme: 'dark',
    terminalTheme: { background: '#05070c', foreground: '#e5e7eb' },
    chartPalette: ['#38bdf8', '#34d399', '#f59e0b', '#fb7185', '#a78bfa'],
    background: { type: 'grid' },
    tokens: tokens({
      color: {
        background: '#0f1115',
        surface: '#151820',
        panel: '#181b22',
        elevated: '#20242c',
        text: '#f3f4f6',
        textMuted: '#c7ccd6',
        border: '#303643',
        accent: '#38bdf8',
        danger: '#fb7185',
        warning: '#f59e0b',
        success: '#34d399',
        info: '#60a5fa',
        codeBackground: '#05070c',
        terminalBackground: '#05070c',
      },
      shadow: {
        panel: '0 1px 2px rgb(0 0 0 / 0.22)',
        floating: '0 18px 42px rgb(0 0 0 / 0.42)',
        focus: '0 0 0 3px rgb(56 189 248 / 0.24)',
      },
      density: 'compact',
    }),
  },
  {
    id: 'cyber-ops',
    name: 'Cyber Ops',
    description: 'High-contrast operational skin with strong status colors.',
    isDark: true,
    syntaxTheme: 'dark',
    terminalTheme: { background: '#020617', foreground: '#d9f99d' },
    chartPalette: ['#22d3ee', '#84cc16', '#f97316', '#f43f5e', '#e879f9'],
    background: { type: 'grid' },
    tokens: tokens({
      color: {
        background: '#020617',
        surface: '#07111f',
        panel: '#0b1526',
        elevated: '#111c31',
        text: '#f8fafc',
        textMuted: '#a7f3d0',
        border: '#164e63',
        accent: '#22d3ee',
        danger: '#f43f5e',
        warning: '#f97316',
        success: '#84cc16',
        info: '#38bdf8',
        codeBackground: '#020617',
        terminalBackground: '#020617',
      },
      density: 'compact',
    }),
  },
  {
    id: 'light-pro',
    name: 'Light Pro',
    description: 'Bright office skin for long reading sessions.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#111827', foreground: '#f9fafb' },
    chartPalette: ['#1d4ed8', '#15803d', '#b45309', '#be123c', '#6d28d9'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#f8fafc',
        surface: '#ffffff',
        panel: '#ffffff',
        elevated: '#f8fafc',
        text: '#0f172a',
        textMuted: '#64748b',
        border: '#e2e8f0',
        accent: '#1d4ed8',
        danger: '#be123c',
        warning: '#b45309',
        success: '#15803d',
        info: '#0284c7',
        codeBackground: '#0f172a',
        terminalBackground: '#111827',
      },
      density: 'comfortable',
    }),
  },
  {
    id: 'terminal',
    name: 'Terminal',
    description: 'Log-first skin with compact spacing and terminal colors.',
    isDark: true,
    syntaxTheme: 'dark',
    terminalTheme: { background: '#000000', foreground: '#f4f4f5' },
    chartPalette: ['#4ade80', '#22d3ee', '#facc15', '#fb7185', '#c084fc'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#050505',
        surface: '#0a0a0a',
        panel: '#111111',
        elevated: '#18181b',
        text: '#f4f4f5',
        textMuted: '#a1a1aa',
        border: '#27272a',
        accent: '#4ade80',
        danger: '#fb7185',
        warning: '#facc15',
        success: '#4ade80',
        info: '#22d3ee',
        codeBackground: '#000000',
        terminalBackground: '#000000',
      },
      density: 'compact',
    }),
  },
  {
    id: 'mobile-focus',
    name: 'Mobile Focus',
    description: 'Spacious small-screen review skin.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#111827', foreground: '#f9fafb' },
    chartPalette: ['#0ea5e9', '#22c55e', '#f59e0b', '#f43f5e', '#8b5cf6'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#f1f5f9',
        surface: '#ffffff',
        panel: '#ffffff',
        elevated: '#f8fafc',
        text: '#111827',
        textMuted: '#64748b',
        border: '#dbe3ef',
        accent: '#0ea5e9',
        danger: '#f43f5e',
        warning: '#f59e0b',
        success: '#22c55e',
        info: '#0ea5e9',
        codeBackground: '#111827',
        terminalBackground: '#111827',
      },
      density: 'spacious',
      radius: {
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
      },
    }),
  },
]

